sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=resources-amazonlinux
  - INSTANCE=resources-centos-6
  - INSTANCE=resources-centos-7
  - INSTANCE=resources-debian-7
  - INSTANCE=resources-debian-8
  - INSTANCE=resources-fedora-latest
  - INSTANCE=resources-ubuntu-1404
  - INSTANCE=resources-ubuntu-1604
  - INSTANCE=resources-opensuse-leap
  - INSTANCE=attributes-amazonlinux
  - INSTANCE=attributes-centos-6
  - INSTANCE=attributes-centos-7
  - INSTANCE=attributes-debian-7
  - INSTANCE=attributes-debian-8
  - INSTANCE=attributes-fedora-latest
  - INSTANCE=attributes-ubuntu-1404
  - INSTANCE=attributes-ubuntu-1604
  - INSTANCE=attributes-opensuse-leap
  - INSTANCE=attributes-conf-file-amazonlinux
  - INSTANCE=attributes-conf-file-centos-6
  - INSTANCE=attributes-conf-file-centos-7
  - INSTANCE=attributes-conf-file-debian-7
  - INSTANCE=attributes-conf-file-debian-8
  - INSTANCE=attributes-conf-file-fedora-latest
  - INSTANCE=attributes-conf-file-ubuntu-1404
  - INSTANCE=attributes-conf-file-ubuntu-1604
  - INSTANCE=attributes-conf-file-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
